title: The Trough
baseline: Your blogging assistant
description: Mostly pinball, some dogs.
baseurl: /
canonicalurl: true
keywords: [pinball, pin2dmd, dogs]
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
