title: The Trough
baseline: Your blogging assistant
description: Mostly pinball, some dogs.
baseurl: http://blog.badbiscuits.co/
canonicalurl: true
keywords: [pinball, pin2dmd, dogs]
author:
date:
  format: j F Y
  timezone: America/New_York
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
